### ISSUE TITLE
trabajo de sistemas numéricos 

### ISSUE THREAD

**Issue by kevinMazarelloJOSE** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-kevinMazarelloJOSE#1]
[TRABAJO DE SISTEMAS NUMERICOS..pdf](https://github.com/user-attachments/files/16842952/TRABAJO.DE.SISTEMAS.NUMERICOS.pdf)

**Comment by irwingsael** [comment]
portada: 25
Procedimiento:25
Figuras, ilustraciones, fotografías: 25
Resultados y conclusiones: 25
Calificación de la practica: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
